import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.scss";
import Header from "@/components/header";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MockEcom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
